baseURL: "http://example.org/"
languageCode: "en-us"
title: "DatadogHQ mock"

# Setting naviagion using the menu system (documentation https://gohugo.io/content-management/menus/)
menu:
  side:
  # Product link (I comment the link name for readability so it's clear where one link start and ends for those who may not use yaml)
   - identifier: Product
     name: Product
     url: "#product"
     Weight: 1
  # Docs link
   - identifier: Docs
     name: Docs
     url: "#docs"
     Weight: 2
  # Pricing link
   - identifier: Pricing
     name: Pricing
     url: "#pricing"
     Weight: 3
  # Customers link
   - identifier: Customers
     name: Customers
     url: "#customers"
     Weight: 4
  # About link
   - identifier: About
     name: About
     url: "#about"
     Weight: 5
  # Blog link
   - identifier: Blog
     name: Blog
     url: "#blog"
     Weight: 6
  # Logo cards
  logos:
    - identifier: airbb
      url: "img/company-logos/airbb.png"
    - identifier: peleton
      url: "img/company-logos/peleton.png"
    - identifier: evernote
      url: "img/company-logos/evernote.png"
    - identifier: samsung
      url: "img/company-logos/samsung.png"
    - identifier: nginx
      url: "img/company-logos/nginx.png"
    - identifier: pagerduty
      url: "img/company-logos/pagerduty.png"
    - identifier: wholefoods
      url: "img/company-logos/wholefoods.png"
    - identifier: att
      url: "img/company-logos/att.png"
  
